"use client";

import { useState } from "react";
import { Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { AvailabilityRuleForm } from "@/components/admin/availability/availability-rule-form";
import { AvailabilityRulesList } from "@/components/admin/availability/availability-rules-list";
import { AvailabilityExceptionForm } from "@/components/admin/availability/availability-exception-form";
import { AvailabilityExceptionsList } from "@/components/admin/availability/availability-exceptions-list";
import type { AvailabilityException, AvailabilityRule } from "@/lib/config/availability";

export function AvailabilityManager({ initialRules, initialExceptions }: { initialRules: AvailabilityRule[]; initialExceptions: AvailabilityException[] }) {
  const [rules, setRules] = useState(initialRules); const [exceptions, setExceptions] = useState(initialExceptions); const [editingRule, setEditingRule] = useState<AvailabilityRule>(); const [editingException, setEditingException] = useState<AvailabilityException>(); const [ruleForm, setRuleForm] = useState(false); const [exceptionForm, setExceptionForm] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function save(nextRules: AvailabilityRule[], nextExceptions: AvailabilityException[]) { setBusy(true); setError(""); try { const response = await fetch("/api/admin/availability", { method:"PUT", headers:{"Content-Type":"application/json"}, body:JSON.stringify({rules:nextRules,exceptions:nextExceptions}) }); const data=await response.json(); if(!response.ok) throw new Error(data.error??"Couldn't save availability."); setRules(data.rules); setExceptions(data.exceptions); setRuleForm(false); setExceptionForm(false); setEditingRule(undefined); setEditingException(undefined); } catch(e){setError(e instanceof Error?e.message:"Couldn't save availability.");} finally{setBusy(false);} }
  function saveRule(rule: AvailabilityRule) { const next=[...rules]; const index=next.findIndex(item=>item.id===rule.id); if(index>=0) next[index]=rule; else next.push(rule); void save(next,exceptions); }
  function disableRule(id:string){void save(rules.map(rule=>rule.id===id?{...rule,active:false}:rule),exceptions);}
  function saveException(exception:AvailabilityException){const next=[...exceptions]; const index=next.findIndex(item=>item.id===exception.id); if(index>=0) next[index]=exception; else next.push(exception); void save(rules,next);}
  function deleteException(id:string){void save(rules,exceptions.filter(item=>item.id!==id));}
  return <div className="space-y-10"><div className="flex justify-end"><Button type="button" onClick={()=>{setEditingRule(undefined);setRuleForm(true);}}><Plus aria-hidden="true" className="size-4"/>Add availability</Button></div>{error&&<p role="alert" className="rounded-xl border border-destructive/30 bg-destructive/5 px-4 py-3 text-sm text-destructive">{error}</p>}<section aria-labelledby="weekly-availability-title"><div className="mb-4"><h2 id="weekly-availability-title" className="text-lg font-semibold">Weekly availability</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">These recurring hours will be used as the starting point for calculating bookable times.</p></div><AvailabilityRulesList rules={rules} onEdit={(rule)=>{setEditingRule(rule);setRuleForm(true);}} onDisable={disableRule} busy={busy}/></section>{ruleForm&&<Card><CardHeader><CardTitle>{editingRule?"Edit availability":"Add availability"}</CardTitle></CardHeader><CardContent><AvailabilityRuleForm key={editingRule?.id??"new"} initialRule={editingRule} onCancel={()=>{setRuleForm(false);setEditingRule(undefined)}} onSubmit={saveRule}/></CardContent></Card>}<section aria-labelledby="availability-exceptions-title"><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 id="availability-exceptions-title" className="text-lg font-semibold">Exceptions</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">Block specific dates or replace your normal hours for a particular date.</p></div><Button type="button" variant="outline" onClick={()=>{setEditingException(undefined);setExceptionForm(true);}}><Plus aria-hidden="true" className="size-4"/>Add exception</Button></div><AvailabilityExceptionsList exceptions={exceptions} onEdit={(exception)=>{setEditingException(exception);setExceptionForm(true);}} onDelete={deleteException} busy={busy}/></section>{exceptionForm&&<Card><CardHeader><CardTitle>{editingException?"Edit exception":"Add exception"}</CardTitle></CardHeader><CardContent><AvailabilityExceptionForm key={editingException?.id??"new"} initialException={editingException} onCancel={()=>{setExceptionForm(false);setEditingException(undefined)}} onSubmit={saveException}/></CardContent></Card>}</div>;
}
