"use client";

import { useEffect, useState } from "react";
import { Check, ExternalLink, ImagePlus, Loader2, Plus, Trash2, X } from "lucide-react";
import { ProfileFaqsField, ProfileResourcesField, ProfileTestimonialsField } from "@/components/admin/profile/profile-content-fields";
import { TimezoneSelect } from "@/components/ui/timezone-select";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import type { EditableTherapistProfile } from "@/lib/cms/site-settings-repository";

type ProfileForm = EditableTherapistProfile;
const emptyProfile: ProfileForm = { name: "", professionalTitle: "Speech-Language Pathologist", shortBio: "", longBio: "", credentials: [], educationQualifications: [], professionalMemberships: [], specialties: [], ageGroups: [], populations: [], languages: ["en", "pt", "hi"], therapyApproach: "", firstSession: "", assessmentInfo: "", referralRequirements: "", accessibility: "", insurancePaymentInfo: "", whyIAmAnSlp: "", testimonials: [], faqs: [], resources: [], location: "", timezone: "Asia/Kolkata", acceptsOnlineAppointments: true, acceptsInPersonAppointments: false, profileImage: "", contact: { email: "", phone: "" }, socialLinks: { website: "", instagram: "", linkedin: "" } };

function isLikelyImageUrl(value: string) { if (value.startsWith("/api/profile/image")) return true; try { const url = new URL(value); return (url.protocol === "http:" || url.protocol === "https:") && /\.(avif|gif|jpe?g|png|webp)(?:$|[?#])/i.test(url.pathname + url.search); } catch { return false; } }
function TagListField({ id, label, hint, placeholder, value, onChange }: { id: string; label: string; hint?: string; placeholder: string; value: string[]; onChange: (value: string[]) => void }) { const [draft, setDraft] = useState(""); function addDraft() { const items = draft.split(",").map((item) => item.trim()).filter(Boolean); if (!items.length) return; onChange([...value, ...items.filter((item) => !value.some((existing) => existing.toLowerCase() === item.toLowerCase()))]); setDraft(""); } return <div className="space-y-2"><Label htmlFor={id}>{label}</Label><div className="rounded-xl border bg-background p-2.5"><div className="flex flex-wrap gap-2">{value.map((item) => <span key={item} className="inline-flex items-center gap-1.5 rounded-full bg-muted px-3 py-1.5 text-sm">{item}<button type="button" onClick={() => onChange(value.filter((current) => current !== item))} className="rounded-full p-0.5 hover:bg-background" aria-label={`Remove ${item}`}><X className="size-3.5" /></button></span>)}</div><div className="mt-2 flex gap-2"><Input id={id} value={draft} onChange={(event) => setDraft(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === ",") { event.preventDefault(); addDraft(); } }} placeholder={placeholder} className="border-0 shadow-none focus-visible:ring-0" /><Button type="button" variant="ghost" size="icon" onClick={addDraft} aria-label={`Add ${label}`}><Plus className="size-4" /></Button></div></div>{hint && <p className="text-xs text-muted-foreground">{hint}</p>}</div>; }
function DetailTextField({ id, label, placeholder, value, onChange, maxLength = 3000 }: { id: string; label: string; placeholder: string; value: string; onChange: (value: string) => void; maxLength?: number }) { return <div className="space-y-2"><Label htmlFor={id}>{label}</Label><Textarea id={id} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} maxLength={maxLength} className="min-h-28" /><p className="text-xs text-muted-foreground">Optional · {value.length}/{maxLength}</p></div>; }

export function ProfileForm() {
  const [values, setValues] = useState<ProfileForm>(emptyProfile); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [uploadingImage, setUploadingImage] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  useEffect(() => { void (async () => { try { const response = await fetch("/api/admin/profile", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "We couldn't load your profile."); setValues(data.profile as ProfileForm); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "We couldn't load your profile."); } finally { setLoading(false); } })(); }, []);
  function update<K extends keyof ProfileForm>(field: K, value: ProfileForm[K]) { setValues((current) => ({ ...current, [field]: value })); setError(""); setNotice(""); }
  async function handleImageUpload(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; setUploadingImage(true); setError(""); setNotice(""); try { const formData = new FormData(); formData.append("file", file); const response = await fetch("/api/admin/profile/image", { method: "POST", body: formData }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "We couldn't upload the profile image."); setValues(data.profile as ProfileForm); setNotice("Profile photo uploaded successfully."); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "We couldn't upload the profile image."); } finally { setUploadingImage(false); } }
  async function removeImage() { setUploadingImage(true); setError(""); setNotice(""); try { const response = await fetch("/api/admin/profile/image", { method: "DELETE" }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "We couldn't remove the profile image."); setValues(data.profile as ProfileForm); setNotice("Profile photo removed."); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "We couldn't remove the profile image."); } finally { setUploadingImage(false); } }
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); setNotice(""); try { const response = await fetch("/api/admin/profile", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "We couldn't save your profile."); setValues(data.profile as ProfileForm); setNotice("Profile saved successfully. Empty sections stay hidden from patients."); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "We couldn't save your profile."); } finally { setSaving(false); } }
  if (loading) return <div className="flex min-h-48 items-center justify-center rounded-2xl border border-dashed"><Loader2 className="size-5 animate-spin text-muted-foreground" aria-hidden="true" /></div>;
  return <div className="grid gap-8 xl:grid-cols-[minmax(0,1fr)_22rem]"><form onSubmit={save} className="min-w-0 space-y-6">
    <Card><CardHeader><CardTitle>Basic information</CardTitle><p className="text-sm text-muted-foreground">Everything here is optional. Add only what you want patients to see.</p></CardHeader><CardContent className="grid gap-6 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="profile-name">Name</Label><Input id="profile-name" value={values.name} onChange={(e) => update("name", e.target.value)} placeholder="Your name" /></div><div className="space-y-2"><Label htmlFor="profile-title">Professional title</Label><Input id="profile-title" value={values.professionalTitle} onChange={(e) => update("professionalTitle", e.target.value)} placeholder="Speech-Language Pathologist" /></div><div className="space-y-2 sm:col-span-2"><Label htmlFor="profile-short-bio">Short bio</Label><Textarea id="profile-short-bio" value={values.shortBio} onChange={(e) => update("shortBio", e.target.value)} placeholder="A warm introduction shown near the top of your website." maxLength={500} /><p className="text-xs text-muted-foreground">Optional · {values.shortBio.length}/500</p></div><div className="space-y-2 sm:col-span-2"><Label htmlFor="profile-long-bio">About you</Label><Textarea id="profile-long-bio" value={values.longBio} onChange={(e) => update("longBio", e.target.value)} placeholder="Share your experience, story and the people you support." maxLength={5000} className="min-h-36" /><p className="text-xs text-muted-foreground">Optional · {values.longBio.length}/5,000</p></div><TagListField id="profile-credentials" label="Credentials" placeholder="Add a credential…" value={values.credentials} onChange={(value) => update("credentials", value)} /><TagListField id="profile-education" label="Education & qualifications" placeholder="Add a qualification…" value={values.educationQualifications} onChange={(value) => update("educationQualifications", value)} /><TagListField id="profile-memberships" label="Professional memberships" placeholder="Add a membership…" value={values.professionalMemberships} onChange={(value) => update("professionalMemberships", value)} /><TagListField id="profile-languages" label="Languages" placeholder="Add a language…" value={values.languages} onChange={(value) => update("languages", value)} /></CardContent></Card>
    <Card><CardHeader><CardTitle>Who you help</CardTitle><p className="text-sm text-muted-foreground">Add specialties such as swallowing or dysphagia, age groups and the people you commonly support. They become clean, patient-friendly tags automatically.</p></CardHeader><CardContent className="grid gap-6 sm:grid-cols-2"><div className="sm:col-span-2"><TagListField id="profile-specialties" label="Areas of expertise & specialties" placeholder="e.g. Dysphagia, swallowing, fluency…" hint="Press Enter or use commas to add several." value={values.specialties} onChange={(value) => update("specialties", value)} /></div><TagListField id="profile-age-groups" label="Age groups" placeholder="e.g. Children…" value={values.ageGroups} onChange={(value) => update("ageGroups", value)} /><TagListField id="profile-populations" label="Who I support" placeholder="e.g. Stroke survivors…" value={values.populations} onChange={(value) => update("populations", value)} /></CardContent></Card>
    <Card><CardHeader><CardTitle>Your clinical approach</CardTitle><p className="text-sm text-muted-foreground">These sections become beautifully formatted information cards automatically. No page design is needed.</p></CardHeader><CardContent className="space-y-6"><DetailTextField id="profile-approach" label="Therapy approach" placeholder="Describe your approach, values and what guides your sessions." value={values.therapyApproach} onChange={(value) => update("therapyApproach", value)} /><DetailTextField id="profile-first-session" label="What happens in the first session" placeholder="Tell patients what they can expect when they first meet you." value={values.firstSession} onChange={(value) => update("firstSession", value)} /><DetailTextField id="profile-assessment" label="Assessment & evaluation" placeholder="Explain assessment options, what they involve and when they may be recommended." value={values.assessmentInfo} onChange={(value) => update("assessmentInfo", value)} /><DetailTextField id="profile-referral" label="Referral requirements" placeholder="For example, whether a referral is needed or self-referrals are welcome." value={values.referralRequirements} onChange={(value) => update("referralRequirements", value)} /></CardContent></Card>
    <Card><CardHeader><CardTitle>Practice information</CardTitle></CardHeader><CardContent className="grid gap-6 sm:grid-cols-2"><DetailTextField id="profile-accessibility" label="Accessibility" placeholder="Share accessibility information patients may find helpful." value={values.accessibility} onChange={(value) => update("accessibility", value)} maxLength={2000} /><DetailTextField id="profile-payment" label="Insurance & payment information" placeholder="Add insurance, payment or reimbursement information you want patients to know." value={values.insurancePaymentInfo} onChange={(value) => update("insurancePaymentInfo", value)} maxLength={2000} /><div className="space-y-2"><Label htmlFor="profile-location">Location / service area</Label><Input id="profile-location" value={values.location} onChange={(e) => update("location", e.target.value)} placeholder="City, country or service area" /></div><TimezoneSelect id="profile-timezone" value={values.timezone} onChange={(value) => update("timezone", value)} /><div className="space-y-3 sm:col-span-2"><p className="text-sm font-medium">Session types</p><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={values.acceptsOnlineAppointments} onChange={(e) => update("acceptsOnlineAppointments", e.target.checked)} className="size-4" /> Online appointments</label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={values.acceptsInPersonAppointments} onChange={(e) => update("acceptsInPersonAppointments", e.target.checked)} className="size-4" /> In-person appointments</label></div></CardContent></Card>
    <Card><CardHeader><CardTitle>Personal note</CardTitle></CardHeader><CardContent><DetailTextField id="profile-why" label="Why I became a speech-language pathologist" placeholder="Share the personal story or motivation you would like patients to know." value={values.whyIAmAnSlp} onChange={(value) => update("whyIAmAnSlp", value)} /></CardContent></Card>
    <Card><CardHeader><CardTitle>Patient-facing content</CardTitle><p className="text-sm text-muted-foreground">Optional. Add testimonials, FAQs and useful resources. The public website handles the layout automatically.</p></CardHeader><CardContent className="space-y-8"><ProfileTestimonialsField value={values.testimonials} onChange={(value) => update("testimonials", value)} /><ProfileFaqsField value={values.faqs} onChange={(value) => update("faqs", value)} /><ProfileResourcesField value={values.resources} onChange={(value) => update("resources", value)} /></CardContent></Card>
    <Card><CardHeader><CardTitle>Profile photo</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-muted-foreground">Upload a professional photo directly. JPG, PNG, WebP or GIF, up to 5 MB.</p><div className="flex flex-wrap items-center gap-3"><label htmlFor="profile-image-upload" className="inline-flex h-9 cursor-pointer items-center gap-2 rounded-lg bg-primary px-3 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/80 has-[:disabled]:pointer-events-none has-[:disabled]:opacity-50"><ImagePlus className="size-4" aria-hidden="true" />{uploadingImage ? "Working…" : "Upload photo"}<input id="profile-image-upload" type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={handleImageUpload} disabled={uploadingImage} className="sr-only" /></label>{values.profileImage && <Button type="button" variant="outline" size="sm" onClick={() => void removeImage()} disabled={uploadingImage}><Trash2 aria-hidden="true" /> Remove photo</Button>}</div>{values.profileImage && <div className="flex items-center gap-4 rounded-xl border p-3"><div className="size-16 shrink-0 rounded-lg bg-muted bg-cover bg-center" style={{ backgroundImage: `url("${values.profileImage.replace(/"/g, "%22")}")` }} aria-label="Profile photo preview" role="img" /><div className="min-w-0"><p className="text-sm font-medium">Photo ready</p><p className="truncate text-xs text-muted-foreground">Your uploaded photo will appear on the public profile.</p></div></div>}<div className="space-y-2"><Label htmlFor="profile-image-url">Or use an image address</Label><Input id="profile-image-url" value={values.profileImage.startsWith("/api/profile/image") ? "" : values.profileImage} onChange={(e) => update("profileImage", e.target.value)} placeholder="Paste a direct image address" /><p className="text-xs text-muted-foreground">Optional. Use the direct address of an image file, not the webpage where the image appears.</p></div></CardContent></Card>
    <Card><CardHeader><CardTitle>Contact &amp; social links</CardTitle></CardHeader><CardContent className="grid gap-6 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="profile-email">Email</Label><Input id="profile-email" type="email" value={values.contact.email} onChange={(e) => update("contact", { ...values.contact, email: e.target.value })} /></div><div className="space-y-2"><Label htmlFor="profile-phone">Phone</Label><Input id="profile-phone" value={values.contact.phone} onChange={(e) => update("contact", { ...values.contact, phone: e.target.value })} /></div><div className="space-y-2"><Label htmlFor="profile-website">Website</Label><Input id="profile-website" type="url" value={values.socialLinks.website} onChange={(e) => update("socialLinks", { ...values.socialLinks, website: e.target.value })} /></div><div className="space-y-2"><Label htmlFor="profile-instagram">Instagram</Label><Input id="profile-instagram" type="url" value={values.socialLinks.instagram} onChange={(e) => update("socialLinks", { ...values.socialLinks, instagram: e.target.value })} /></div><div className="space-y-2 sm:col-span-2"><Label htmlFor="profile-linkedin">LinkedIn</Label><Input id="profile-linkedin" type="url" value={values.socialLinks.linkedin} onChange={(e) => update("socialLinks", { ...values.socialLinks, linkedin: e.target.value })} /></div></CardContent></Card>
    {error && <div role="alert" className="rounded-xl border border-destructive/30 bg-destructive/5 px-4 py-3 text-sm text-destructive">{error}</div>}{notice && <div role="status" className="rounded-xl border bg-primary/5 px-4 py-3 text-sm">{notice}</div>}<div className="flex justify-end"><Button type="submit" disabled={saving || uploadingImage}>{saving ? <Loader2 className="animate-spin" aria-hidden="true" /> : <Check aria-hidden="true" />} {saving ? "Saving…" : "Save profile"}</Button></div>
  </form>
  <Card className="h-fit xl:sticky xl:top-6"><CardHeader><CardTitle>Public preview</CardTitle><p className="text-sm text-muted-foreground">The website automatically arranges the information you add. Empty sections stay out of the page.</p></CardHeader><CardContent><div className="overflow-hidden rounded-2xl border bg-background"><div className="flex aspect-[4/3] items-center justify-center bg-muted/40" style={isLikelyImageUrl(values.profileImage) ? { backgroundImage: `url("${values.profileImage.replace(/"/g, "%22")}")`, backgroundPosition: "center", backgroundSize: "cover" } : undefined}>{!isLikelyImageUrl(values.profileImage) && <span className="px-6 text-center text-xs text-muted-foreground">Upload a professional photo to show it here.</span>}</div><div className="space-y-3 p-5"><div><p className="text-lg font-semibold">{values.name || "Your name"}</p><p className="text-sm text-muted-foreground">{values.professionalTitle || "Professional title"}</p></div>{values.shortBio && <p className="text-sm leading-6 text-muted-foreground">{values.shortBio}</p>}{values.specialties.length > 0 && <div className="flex flex-wrap gap-1.5">{values.specialties.slice(0, 5).map((item) => <span key={item} className="rounded-full bg-muted px-2 py-1 text-[11px]">{item}</span>)}</div>}</div></div><a href="/" target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 text-sm font-medium underline-offset-4 hover:underline">Open public profile <ExternalLink className="size-3.5" aria-hidden="true" /></a></CardContent></Card>
  </div>;
}
