"use client";

import { useEffect, useState } from "react";
import { Check, ExternalLink, Loader2 } from "lucide-react";
import { TimezoneSelect } from "@/components/ui/timezone-select";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import type { EditableTherapistProfile } from "@/lib/cms/site-settings-repository";

type ProfileForm = EditableTherapistProfile;
const emptyProfile: ProfileForm = { name: "", professionalTitle: "Speech-Language Pathologist", shortBio: "", longBio: "", credentials: [], languages: ["en", "pt", "hi"], location: "", timezone: "Asia/Kolkata", acceptsOnlineAppointments: true, acceptsInPersonAppointments: false, profileImage: "", contact: { email: "", phone: "" }, socialLinks: { website: "", instagram: "", linkedin: "" } };
function listValue(items: string[]) { return items.join(", "); }
function parseList(value: string) { return value.split(",").map((item) => item.trim()).filter(Boolean); }
function isLikelyImageUrl(value: string) { try { const url = new URL(value); return (url.protocol === "http:" || url.protocol === "https:") && /\.(avif|gif|jpe?g|png|webp)(?:$|[?#])/i.test(url.pathname + url.search); } catch { return false; } }

export function ProfileForm() {
  const [values, setValues] = useState<ProfileForm>(emptyProfile); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  useEffect(() => { void (async () => { try { const response = await fetch("/api/admin/profile", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "We couldn't load your profile."); setValues(data.profile as ProfileForm); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "We couldn't load your profile."); } finally { setLoading(false); } })(); }, []);
  function update<K extends keyof ProfileForm>(field: K, value: ProfileForm[K]) { setValues((current) => ({ ...current, [field]: value })); setError(""); setNotice(""); }
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); setNotice(""); try { const response = await fetch("/api/admin/profile", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "We couldn't save your profile."); setValues(data.profile as ProfileForm); setNotice("Profile saved successfully."); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "We couldn't save your profile."); } finally { setSaving(false); } }
  if (loading) return <div className="flex min-h-48 items-center justify-center rounded-2xl border border-dashed"><Loader2 className="size-5 animate-spin text-muted-foreground" aria-hidden="true" /></div>;
  return <div className="grid gap-8 xl:grid-cols-[minmax(0,1fr)_22rem]"><form onSubmit={save} className="min-w-0 space-y-6">
    <Card><CardHeader><CardTitle>Basic information</CardTitle></CardHeader><CardContent className="grid gap-6 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="profile-name">Name</Label><Input id="profile-name" value={values.name} onChange={(e) => update("name", e.target.value)} placeholder="Your name" /></div><div className="space-y-2"><Label htmlFor="profile-title">Professional title</Label><Input id="profile-title" value={values.professionalTitle} onChange={(e) => update("professionalTitle", e.target.value)} required /></div><div className="space-y-2 sm:col-span-2"><Label htmlFor="profile-short-bio">Short bio</Label><Textarea id="profile-short-bio" value={values.shortBio} onChange={(e) => update("shortBio", e.target.value)} placeholder="A short introduction shown near the top of your website." maxLength={500} /><p className="text-xs text-muted-foreground">{values.shortBio.length}/500 characters</p></div><div className="space-y-2 sm:col-span-2"><Label htmlFor="profile-long-bio">About you</Label><Textarea id="profile-long-bio" value={values.longBio} onChange={(e) => update("longBio", e.target.value)} placeholder="Share your approach, experience and the people you support." maxLength={5000} className="min-h-36" /><p className="text-xs text-muted-foreground">{values.longBio.length}/5,000 characters</p></div><div className="space-y-2"><Label htmlFor="profile-credentials">Credentials</Label><Input id="profile-credentials" value={listValue(values.credentials)} onChange={(e) => update("credentials", parseList(e.target.value))} placeholder="MSc, CCC-SLP, Licensed SLP" /><p className="text-xs text-muted-foreground">Separate each credential with a comma.</p></div><div className="space-y-2"><Label htmlFor="profile-languages">Languages</Label><Input id="profile-languages" value={listValue(values.languages)} onChange={(e) => update("languages", parseList(e.target.value))} placeholder="English, Portuguese, Hindi" /><p className="text-xs text-muted-foreground">Use the names you want patients to see.</p></div></CardContent></Card>
    <Card><CardHeader><CardTitle>Practice details</CardTitle></CardHeader><CardContent className="grid gap-6 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="profile-location">Location</Label><Input id="profile-location" value={values.location} onChange={(e) => update("location", e.target.value)} placeholder="City, country or service area" /></div><TimezoneSelect id="profile-timezone" value={values.timezone} onChange={(value) => update("timezone", value)} required /><div className="space-y-3 sm:col-span-2"><p className="text-sm font-medium">Session types</p><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={values.acceptsOnlineAppointments} onChange={(e) => update("acceptsOnlineAppointments", e.target.checked)} className="size-4" /> Online appointments</label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={values.acceptsInPersonAppointments} onChange={(e) => update("acceptsInPersonAppointments", e.target.checked)} className="size-4" /> In-person appointments</label></div><div className="space-y-2 sm:col-span-2"><Label htmlFor="profile-image">Profile image</Label><Input id="profile-image" value={values.profileImage} onChange={(e) => update("profileImage", e.target.value)} placeholder="Paste the direct image address" /><p className="text-xs text-muted-foreground">Use the direct address of an image file (for example, ending in .jpg or .png), not the webpage where the image appears.</p></div></CardContent></Card>
    <Card><CardHeader><CardTitle>Contact &amp; social links</CardTitle></CardHeader><CardContent className="grid gap-6 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="profile-email">Email</Label><Input id="profile-email" type="email" value={values.contact.email} onChange={(e) => update("contact", { ...values.contact, email: e.target.value })} /></div><div className="space-y-2"><Label htmlFor="profile-phone">Phone</Label><Input id="profile-phone" value={values.contact.phone} onChange={(e) => update("contact", { ...values.contact, phone: e.target.value })} /></div><div className="space-y-2"><Label htmlFor="profile-website">Website</Label><Input id="profile-website" type="url" value={values.socialLinks.website} onChange={(e) => update("socialLinks", { ...values.socialLinks, website: e.target.value })} /></div><div className="space-y-2"><Label htmlFor="profile-instagram">Instagram</Label><Input id="profile-instagram" type="url" value={values.socialLinks.instagram} onChange={(e) => update("socialLinks", { ...values.socialLinks, instagram: e.target.value })} /></div><div className="space-y-2 sm:col-span-2"><Label htmlFor="profile-linkedin">LinkedIn</Label><Input id="profile-linkedin" type="url" value={values.socialLinks.linkedin} onChange={(e) => update("socialLinks", { ...values.socialLinks, linkedin: e.target.value })} /></div></CardContent></Card>
    {error && <div role="alert" className="rounded-xl border border-destructive/30 bg-destructive/5 px-4 py-3 text-sm text-destructive">{error}</div>}{notice && <div role="status" className="rounded-xl border bg-primary/5 px-4 py-3 text-sm">{notice}</div>}<div className="flex justify-end"><Button type="submit" disabled={saving}>{saving ? <Loader2 className="animate-spin" aria-hidden="true" /> : <Check aria-hidden="true" />} {saving ? "Saving…" : "Save profile"}</Button></div>
  </form>
  <Card className="h-fit xl:sticky xl:top-6"><CardHeader><CardTitle>Public preview</CardTitle><p className="text-sm text-muted-foreground">A quick view of how the main profile information will appear to patients.</p></CardHeader><CardContent><div className="overflow-hidden rounded-2xl border bg-background"><div className="flex aspect-[4/3] items-center justify-center bg-muted/40" style={isLikelyImageUrl(values.profileImage) ? { backgroundImage: `url(${values.profileImage})`, backgroundPosition: "center", backgroundSize: "cover" } : undefined}>{!isLikelyImageUrl(values.profileImage) && <span className="px-6 text-center text-xs text-muted-foreground">Add a direct image address to show your profile photo here.</span>}</div><div className="space-y-3 p-5"><div><p className="text-lg font-semibold">{values.name || "Your name"}</p><p className="text-sm text-muted-foreground">{values.professionalTitle || "Professional title"}</p></div>{values.shortBio && <p className="text-sm leading-6 text-muted-foreground">{values.shortBio}</p>}{(values.location || values.timezone) && <p className="text-xs text-muted-foreground">{[values.location, values.timezone].filter(Boolean).join(" · ")}</p>}<div className="flex flex-wrap gap-2">{values.acceptsOnlineAppointments && <span className="rounded-full border px-2.5 py-1 text-xs">Online</span>}{values.acceptsInPersonAppointments && <span className="rounded-full border px-2.5 py-1 text-xs">In person</span>}</div>{values.credentials.length > 0 && <p className="text-xs text-muted-foreground">{values.credentials.join(" · ")}</p>}</div></div><a href="/" target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 text-sm font-medium underline-offset-4 hover:underline">Open public profile <ExternalLink className="size-3.5" aria-hidden="true" /></a></CardContent></Card>
  </div>;
}
