"use client";

import * as React from "react";
import { Check, ExternalLink, ImagePlus, Loader2, Save, Sparkles, Trash2, X } from "lucide-react";
import { ProfileFaqsField, ProfileResourcesField, ProfileTestimonialsField } from "@/components/admin/profile/profile-content-fields";
import { TimezoneSelect } from "@/components/ui/timezone-select";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import type { EditableTherapistProfile } from "@/lib/cms/site-settings-repository";

type ProfileForm = EditableTherapistProfile;
const emptyProfile: ProfileForm = { name: "", professionalTitle: "Speech-Language Pathologist", shortBio: "", longBio: "", credentials: [], educationQualifications: [], professionalMemberships: [], specialties: [], ageGroups: [], populations: [], languages: ["en", "pt", "hi"], therapyApproach: "", firstSession: "", assessmentInfo: "", referralRequirements: "", accessibility: "", insurancePaymentInfo: "", whyIAmAnSlp: "", testimonials: [], faqs: [], resources: [], location: "", timezone: "Asia/Kolkata", acceptsOnlineAppointments: true, acceptsInPersonAppointments: false, profileImage: "", contact: { email: "", phone: "" }, socialLinks: { website: "", instagram: "", linkedin: "" } };

function TagListField({ id, label, hint, placeholder, value, onChange }: { id: string; label: string; hint?: string; placeholder: string; value: string[]; onChange: (value: string[]) => void }) {
  const [draft, setDraft] = React.useState("");
  function addDraft() { const items = draft.split(",").map((item) => item.trim()).filter(Boolean); if (!items.length) return; onChange([...value, ...items.filter((item) => !value.some((existing) => existing.toLowerCase() === item.toLowerCase()))]); setDraft(""); }
  return <div className="space-y-2"><Label>{label}</Label><div className="rounded-xl border bg-background p-2.5"><div className="flex flex-wrap gap-2">{value.map((item) => <span key={item} className="inline-flex items-center gap-1.5 rounded-full bg-muted px-3 py-1.5 text-sm">{item}<button type="button" onClick={() => onChange(value.filter((current) => current !== item))} className="rounded-full p-0.5 hover:bg-background" aria-label={`Remove ${item}`}><X className="size-3.5" /></button></span>)}</div><div className="mt-2 flex gap-2"><Input id={id} value={draft} onChange={(event) => setDraft(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === ",") { event.preventDefault(); addDraft(); } }} placeholder={placeholder} className="border-0 shadow-none focus-visible:ring-0" /><Button type="button" variant="ghost" size="icon" onClick={addDraft} aria-label={`Add ${label}`}><PlusIcon /></Button></div></div>{hint && <p className="text-xs text-muted-foreground">{hint}</p>}</div>;
}
function PlusIcon() { return <span aria-hidden="true" className="text-lg leading-none">+</span>; }
function DetailTextField({ id, label, placeholder, value, onChange, maxLength = 3000 }: { id: string; label: string; placeholder: string; value: string; onChange: (value: string) => void; maxLength?: number }) { return <div className="space-y-2"><Label htmlFor={id}>{label}</Label><Textarea id={id} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} maxLength={maxLength} className="min-h-28" /><p className="text-xs text-muted-foreground">Optional · {value.length}/{maxLength}</p></div>; }

export function ProfileForm() {
  const [values, setValues] = React.useState<ProfileForm>(emptyProfile); const [loading, setLoading] = React.useState(true); const [saving, setSaving] = React.useState(false); const [publishing, setPublishing] = React.useState(false); const [previewOpen, setPreviewOpen] = React.useState(false); const [uploadingImage, setUploadingImage] = React.useState(false); const [status, setStatus] = React.useState("Loading draft…"); const [error, setError] = React.useState(""); const [lastSaved, setLastSaved] = React.useState("");
  React.useEffect(() => { void (async () => { try { const response = await fetch("/api/admin/profile", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "We couldn't load your profile draft."); setValues(data.profile as ProfileForm); setLastSaved(JSON.stringify(data.profile)); setStatus("Draft ready"); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "We couldn't load your profile draft."); } finally { setLoading(false); } })(); }, []);
  React.useEffect(() => { if (loading) return; setStatus("Changes waiting to save…"); const timer = window.setTimeout(() => { void (async () => { setSaving(true); setError(""); try { const response = await fetch("/api/admin/profile", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "We couldn't save your draft."); setValues(data.profile as ProfileForm); setLastSaved(JSON.stringify(data.profile)); setStatus("Draft saved automatically"); setSaving(false); } catch (requestError) { setSaving(false); setStatus("Draft not saved"); setError(requestError instanceof Error ? requestError.message : "We couldn't save your draft."); } })(); }, 1200); return () => window.clearTimeout(timer); }, [values, loading]);
  function update<K extends keyof ProfileForm>(field: K, value: ProfileForm[K]) { setValues((current) => ({ ...current, [field]: value })); setError(""); }
  async function handleImageUpload(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; setUploadingImage(true); setError(""); try { const formData = new FormData(); formData.append("file", file); const response = await fetch("/api/admin/profile/image", { method: "POST", body: formData }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "We couldn't upload the profile image."); setValues(data.profile as ProfileForm); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "We couldn't upload the profile image."); } finally { setUploadingImage(false); } }
  async function removeImage() { setUploadingImage(true); setError(""); try { const response = await fetch("/api/admin/profile/image", { method: "DELETE" }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "We couldn't remove the profile image."); setValues(data.profile as ProfileForm); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "We couldn't remove the profile image."); } finally { setUploadingImage(false); } }
  async function publish() { setPublishing(true); setError(""); try { const response = await fetch("/api/admin/profile", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "publish" }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "We couldn't publish your changes."); setValues(data.profile as ProfileForm); setLastSaved(JSON.stringify(data.profile)); setStatus("Published — patients can now see these changes"); setPreviewOpen(false); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "We couldn't publish your changes."); } finally { setPublishing(false); } }
  if (loading) return <div className="flex min-h-48 items-center justify-center rounded-2xl border border-dashed"><Loader2 className="size-5 animate-spin text-muted-foreground" aria-hidden="true" /></div>;
  const hasUnpublishedChanges = JSON.stringify(values) !== lastSaved;
  return <div className="space-y-6"><div className="sticky top-2 z-30 rounded-2xl border bg-background/95 p-3 shadow-sm backdrop-blur sm:p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2 text-sm font-medium"><span className={`size-2 rounded-full ${hasUnpublishedChanges || saving ? "bg-amber-500" : "bg-emerald-500"}`} />{status}</div><p className="mt-1 text-xs text-muted-foreground">Your draft is private. Nothing reaches patients until you publish it.</p></div><div className="flex flex-wrap gap-2"><Button type="button" variant="outline" onClick={() => setPreviewOpen(true)}><Sparkles /> Preview draft</Button><Button type="button" onClick={() => setPreviewOpen(true)} disabled={saving || publishing}><Check /> Review &amp; publish</Button></div></div></div>{error && <div className="rounded-xl border border-destructive/30 bg-destructive/5 px-4 py-3 text-sm text-destructive">{error}</div>}
    <form onSubmit={(event) => event.preventDefault()} className="min-w-0 space-y-6">
      <Card><CardHeader><CardTitle>Basic information</CardTitle><p className="text-sm text-muted-foreground">Everything here is optional. Add only what you want patients to see.</p></CardHeader><CardContent className="grid gap-6 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="profile-name">Name</Label><Input id="profile-name" value={values.name} onChange={(e) => update("name", e.target.value)} placeholder="Your name" /></div><div className="space-y-2"><Label htmlFor="profile-title">Professional title</Label><Input id="profile-title" value={values.professionalTitle} onChange={(e) => update("professionalTitle", e.target.value)} placeholder="Speech-Language Pathologist" /></div><div className="space-y-2 sm:col-span-2"><Label htmlFor="profile-short-bio">Short bio</Label><Textarea id="profile-short-bio" value={values.shortBio} onChange={(e) => update("shortBio", e.target.value)} placeholder="A warm introduction shown near the top of your website." maxLength={500} /><p className="text-xs text-muted-foreground">Optional · {values.shortBio.length}/500</p></div><div className="space-y-2 sm:col-span-2"><Label htmlFor="profile-long-bio">About you</Label><Textarea id="profile-long-bio" value={values.longBio} onChange={(e) => update("longBio", e.target.value)} placeholder="Share your experience, story and the people you support." maxLength={5000} className="min-h-36" /><p className="text-xs text-muted-foreground">Optional · {values.longBio.length}/5,000</p></div><TagListField id="profile-credentials" label="Credentials" placeholder="Add a credential…" value={values.credentials} onChange={(value) => update("credentials", value)} /><TagListField id="profile-education" label="Education & qualifications" placeholder="Add a qualification…" value={values.educationQualifications} onChange={(value) => update("educationQualifications", value)} /><TagListField id="profile-memberships" label="Professional memberships" placeholder="Add a membership…" value={values.professionalMemberships} onChange={(value) => update("professionalMemberships", value)} /><TagListField id="profile-languages" label="Languages" placeholder="Add a language…" value={values.languages} onChange={(value) => update("languages", value)} /></CardContent></Card>
      <Card><CardHeader><CardTitle>Who you help</CardTitle><p className="text-sm text-muted-foreground">Add specialties such as swallowing or dysphagia, age groups and the people you commonly support.</p></CardHeader><CardContent className="grid gap-6 sm:grid-cols-2"><div className="sm:col-span-2"><TagListField id="profile-specialties" label="Areas of expertise & specialties" placeholder="e.g. Dysphagia, swallowing, fluency…" hint="Press Enter or use commas to add several." value={values.specialties} onChange={(value) => update("specialties", value)} /></div><TagListField id="profile-age-groups" label="Age groups" placeholder="e.g. Children…" value={values.ageGroups} onChange={(value) => update("ageGroups", value)} /><TagListField id="profile-populations" label="Who I support" placeholder="e.g. Stroke survivors…" value={values.populations} onChange={(value) => update("populations", value)} /></CardContent></Card>
      <Card><CardHeader><CardTitle>Your clinical approach</CardTitle></CardHeader><CardContent className="space-y-6"><DetailTextField id="profile-approach" label="Therapy approach" placeholder="Describe your approach, values and what guides your sessions." value={values.therapyApproach} onChange={(value) => update("therapyApproach", value)} /><DetailTextField id="profile-first-session" label="What happens in the first session" placeholder="Tell patients what they can expect when they first meet you." value={values.firstSession} onChange={(value) => update("firstSession", value)} /><DetailTextField id="profile-assessment" label="Assessment & evaluation" placeholder="Explain assessment options and when they may be recommended." value={values.assessmentInfo} onChange={(value) => update("assessmentInfo", value)} /><DetailTextField id="profile-referral" label="Referral requirements" placeholder="For example, whether a referral is needed or self-referrals are welcome." value={values.referralRequirements} onChange={(value) => update("referralRequirements", value)} /></CardContent></Card>
      <Card><CardHeader><CardTitle>Practice information</CardTitle></CardHeader><CardContent className="grid gap-6 sm:grid-cols-2"><DetailTextField id="profile-accessibility" label="Accessibility" placeholder="Share accessibility information patients may find helpful." value={values.accessibility} onChange={(value) => update("accessibility", value)} maxLength={2000} /><DetailTextField id="profile-payment" label="Insurance & payment information" placeholder="Add insurance, payment or reimbursement information." value={values.insurancePaymentInfo} onChange={(value) => update("insurancePaymentInfo", value)} maxLength={2000} /><div className="space-y-2"><Label htmlFor="profile-location">Location / service area</Label><Input id="profile-location" value={values.location} onChange={(e) => update("location", e.target.value)} placeholder="City, country or service area" /></div><TimezoneSelect id="profile-timezone" value={values.timezone} onChange={(value) => update("timezone", value)} /><div className="space-y-3 sm:col-span-2"><p className="text-sm font-medium">Session types</p><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={values.acceptsOnlineAppointments} onChange={(e) => update("acceptsOnlineAppointments", e.target.checked)} className="size-4" /> Online appointments</label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={values.acceptsInPersonAppointments} onChange={(e) => update("acceptsInPersonAppointments", e.target.checked)} className="size-4" /> In-person appointments</label></div></CardContent></Card>
      <Card><CardHeader><CardTitle>Personal note</CardTitle></CardHeader><CardContent><DetailTextField id="profile-why" label="Why I became a speech-language pathologist" placeholder="Share the personal story or motivation you would like patients to know." value={values.whyIAmAnSlp} onChange={(value) => update("whyIAmAnSlp", value)} /></CardContent></Card>
      <Card><CardHeader><CardTitle>Patient-facing content</CardTitle><p className="text-sm text-muted-foreground">Add one testimonial, FAQ or resource at a time. Saved entries stay below the form for easy editing.</p></CardHeader><CardContent className="space-y-10"><ProfileTestimonialsField value={values.testimonials} onChange={(value) => update("testimonials", value)} /><ProfileFaqsField value={values.faqs} onChange={(value) => update("faqs", value)} /><ProfileResourcesField value={values.resources} onChange={(value) => update("resources", value)} /></CardContent></Card>
      <Card><CardHeader><CardTitle>Profile photo</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-muted-foreground">Photos also remain private until the draft is published.</p><div className="flex flex-wrap items-center gap-3"><label htmlFor="profile-image-upload" className="inline-flex h-9 cursor-pointer items-center gap-2 rounded-lg bg-primary px-3 text-sm font-medium text-primary-foreground hover:opacity-90"><ImagePlus className="size-4" />{uploadingImage ? "Working…" : "Upload photo"}<input id="profile-image-upload" type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={handleImageUpload} disabled={uploadingImage} className="sr-only" /></label>{values.profileImage && <Button type="button" variant="outline" size="sm" onClick={() => void removeImage()} disabled={uploadingImage}><Trash2 /> Remove photo</Button>}</div>{values.profileImage && <div className="flex items-center gap-4 rounded-xl border p-3"><div className="size-16 shrink-0 rounded-lg bg-muted bg-cover bg-center" style={{ backgroundImage: `url("${values.profileImage.replace(/"/g, "%22")}")` }} role="img" aria-label="Profile photo preview" /><p className="text-sm text-muted-foreground">Draft photo ready for review.</p></div>}<div className="space-y-2"><Label htmlFor="profile-image-url">Or use an image address</Label><Input id="profile-image-url" value={values.profileImage.startsWith("/api/profile/image") ? "" : values.profileImage} onChange={(e) => update("profileImage", e.target.value)} placeholder="Paste a direct image address" /><p className="text-xs text-muted-foreground">Use the direct address of an image file, not the webpage where the image appears.</p></div></CardContent></Card>
      <Card><CardHeader><CardTitle>Contact &amp; social links</CardTitle></CardHeader><CardContent className="grid gap-6 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="profile-email">Email</Label><Input id="profile-email" type="email" value={values.contact.email} onChange={(e) => update("contact", { ...values.contact, email: e.target.value })} /></div><div className="space-y-2"><Label htmlFor="profile-phone">Phone</Label><Input id="profile-phone" value={values.contact.phone} onChange={(e) => update("contact", { ...values.contact, phone: e.target.value })} /></div><div className="space-y-2"><Label htmlFor="profile-website">Website</Label><Input id="profile-website" value={values.socialLinks.website} onChange={(e) => update("socialLinks", { ...values.socialLinks, website: e.target.value })} placeholder="https://…" /></div><div className="space-y-2"><Label htmlFor="profile-instagram">Instagram</Label><Input id="profile-instagram" value={values.socialLinks.instagram} onChange={(e) => update("socialLinks", { ...values.socialLinks, instagram: e.target.value })} placeholder="https://…" /></div><div className="space-y-2"><Label htmlFor="profile-linkedin">LinkedIn</Label><Input id="profile-linkedin" value={values.socialLinks.linkedin} onChange={(e) => update("socialLinks", { ...values.socialLinks, linkedin: e.target.value })} placeholder="https://…" /></div></CardContent></Card>
    </form>
    {previewOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-0 sm:p-6"><div className="flex h-full w-full flex-col overflow-hidden bg-background sm:h-[92vh] sm:max-w-6xl sm:rounded-2xl sm:border sm:shadow-2xl"><div className="flex shrink-0 items-center justify-between gap-3 border-b px-4 py-3"><div><p className="font-semibold">Preview your draft</p><p className="text-xs text-muted-foreground">Patients see the published version until you publish this draft.</p></div><div className="flex items-center gap-2"><a href="/admin/profile/preview" target="_blank" rel="noreferrer" className="inline-flex h-9 items-center gap-2 rounded-lg border px-3 text-sm font-medium"><ExternalLink className="size-4" /> Open full preview</a><Button type="button" variant="ghost" size="icon" onClick={() => setPreviewOpen(false)} aria-label="Close preview"><X /></Button></div></div><iframe title="Draft website preview" src="/admin/profile/preview" className="min-h-0 flex-1 border-0 bg-background" /><div className="flex shrink-0 flex-col-reverse gap-2 border-t bg-background p-3 sm:flex-row sm:items-center sm:justify-end"><Button type="button" variant="outline" onClick={() => setPreviewOpen(false)}>Keep editing</Button><Button type="button" onClick={() => void publish()} disabled={publishing || saving}><Check /> {publishing ? "Publishing…" : "Publish changes"}</Button></div></div></div>}
  </div>;
}
