import { Accessibility, BookOpenCheck, CheckCircle2, ClipboardCheck, HeartHandshake, Languages, GraduationCap, Sparkles, UsersRound } from "lucide-react";
import type { EditableTherapistProfile } from "@/lib/cms/site-settings-repository";

function DetailPills({ items }: { items: string[] }) {
  if (!items.length) return null;
  return <div className="flex flex-wrap gap-2.5">{items.map((item) => <span key={item} className="rounded-full border bg-background px-3.5 py-2 text-sm leading-5 shadow-sm">{item}</span>)}</div>;
}

function DetailCard({ icon: Icon, title, children }: { icon: typeof Sparkles; title: string; children: React.ReactNode }) {
  return <article className="rounded-2xl border bg-card/60 p-6 shadow-sm sm:p-7"><div className="flex items-center gap-3"><div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-muted"><Icon className="size-5" aria-hidden="true" /></div><h3 className="text-lg font-semibold tracking-tight">{title}</h3></div><div className="mt-5 text-sm leading-7 text-muted-foreground">{children}</div></article>;
}

export function ProfileDetails({ therapistProfile }: { therapistProfile: EditableTherapistProfile }) {
  const hasWhoIHelp = therapistProfile.ageGroups.length > 0 || therapistProfile.populations.length > 0;
  const hasProfessionalDetails = therapistProfile.educationQualifications.length > 0 || therapistProfile.professionalMemberships.length > 0 || therapistProfile.languages.length > 0;
  const hasPracticalDetails = therapistProfile.firstSession || therapistProfile.assessmentInfo || therapistProfile.referralRequirements || therapistProfile.accessibility || therapistProfile.insurancePaymentInfo;
  const hasDetails = therapistProfile.specialties.length > 0 || hasWhoIHelp || therapistProfile.therapyApproach || hasProfessionalDetails || hasPracticalDetails || therapistProfile.whyIAmAnSlp;
  if (!hasDetails) return null;

  return <section aria-labelledby="profile-details-title" className="border-t py-20 sm:py-24"><div className="mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><p className="text-sm font-medium text-muted-foreground">More about the practice</p><h2 id="profile-details-title" className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">A little more about how I work</h2><p className="mt-4 text-base leading-7 text-muted-foreground sm:text-lg">Explore the areas of support, people served and practical details that matter when choosing a speech and language professional.</p></div>
    <div className="mt-12 space-y-12">
      {therapistProfile.specialties.length > 0 && <div><div className="mb-5 flex items-center gap-2"><Sparkles className="size-5" aria-hidden="true" /><h3 className="text-xl font-semibold">Areas of expertise</h3></div><DetailPills items={therapistProfile.specialties} /></div>}
      {hasWhoIHelp && <div className="grid gap-6 lg:grid-cols-2">{therapistProfile.ageGroups.length > 0 && <DetailCard icon={UsersRound} title="Age groups"> <DetailPills items={therapistProfile.ageGroups} /></DetailCard>}{therapistProfile.populations.length > 0 && <DetailCard icon={HeartHandshake} title="Who I support"><DetailPills items={therapistProfile.populations} /></DetailCard>}</div>}
      {therapistProfile.therapyApproach && <DetailCard icon={HeartHandshake} title="My approach"><p className="whitespace-pre-line">{therapistProfile.therapyApproach}</p></DetailCard>}
      {hasProfessionalDetails && <div className="grid gap-6 lg:grid-cols-2">{therapistProfile.educationQualifications.length > 0 && <DetailCard icon={GraduationCap} title="Education & qualifications"><ul className="space-y-2">{therapistProfile.educationQualifications.map((item) => <li key={item} className="flex items-start gap-2"><CheckCircle2 className="mt-1 size-4 shrink-0" aria-hidden="true" /><span>{item}</span></li>)}</ul></DetailCard>}{therapistProfile.professionalMemberships.length > 0 && <DetailCard icon={BookOpenCheck} title="Professional memberships"><ul className="space-y-2">{therapistProfile.professionalMemberships.map((item) => <li key={item} className="flex items-start gap-2"><CheckCircle2 className="mt-1 size-4 shrink-0" aria-hidden="true" /><span>{item}</span></li>)}</ul></DetailCard>}{therapistProfile.languages.length > 0 && <DetailCard icon={Languages} title="Languages"><DetailPills items={therapistProfile.languages.map((language) => ({ en: "English", hi: "Hindi", pt: "Portuguese", ml: "Malayalam", ta: "Tamil", te: "Telugu", kn: "Kannada" } as Record<string, string>)[language.toLowerCase()] ?? language)} /></DetailCard>}</div>}
      {hasPracticalDetails && <div className="grid gap-6 lg:grid-cols-2">{therapistProfile.firstSession && <DetailCard icon={ClipboardCheck} title="What to expect in the first session"><p className="whitespace-pre-line">{therapistProfile.firstSession}</p></DetailCard>}{therapistProfile.assessmentInfo && <DetailCard icon={ClipboardCheck} title="Assessment & evaluation"><p className="whitespace-pre-line">{therapistProfile.assessmentInfo}</p></DetailCard>}{therapistProfile.referralRequirements && <DetailCard icon={BookOpenCheck} title="Referrals"><p className="whitespace-pre-line">{therapistProfile.referralRequirements}</p></DetailCard>}{therapistProfile.accessibility && <DetailCard icon={Accessibility} title="Accessibility"><p className="whitespace-pre-line">{therapistProfile.accessibility}</p></DetailCard>}{therapistProfile.insurancePaymentInfo && <DetailCard icon={HeartHandshake} title="Insurance & payment"><p className="whitespace-pre-line">{therapistProfile.insurancePaymentInfo}</p></DetailCard>}</div>}
      {therapistProfile.whyIAmAnSlp && <div className="rounded-3xl border bg-muted/40 p-7 sm:p-10"><p className="text-sm font-medium text-muted-foreground">A personal note</p><h3 className="mt-2 text-2xl font-semibold tracking-tight">Why I became a speech-language pathologist</h3><p className="mt-5 max-w-3xl whitespace-pre-line text-base leading-8 text-muted-foreground sm:text-lg">{therapistProfile.whyIAmAnSlp}</p></div>}
    </div></div></section>;
}
