import type { Collection } from "mongodb";
import { GridFSBucket } from "mongodb";
import { getMongoDb } from "@/lib/db/mongodb";
import { bookingSettings, type BookingSettings, validateBookingSettings } from "@/lib/config/booking-settings";
import { therapistProfile } from "@/lib/config/therapist-profile";

const collectionName = "site_settings";
const profileId = "therapist-profile";
const profileDraftId = "therapist-profile-draft";
const bookingSettingsId = "booking-settings";
const profileMediaBucket = "profile_media";
const publishedImageFile = "therapist-profile-image";
const draftImageFile = "therapist-profile-image-draft";
type StoredDocument<T> = { _id: string; value: T; updatedAt: Date };
export type ProfileTestimonial = { quote: string; name: string; context: string };
export type ProfileFaqItem = { question: string; answer: string };
export type ProfileResource = { title: string; description: string; url: string };
export type EditableTherapistProfile = { name: string; professionalTitle: string; shortBio: string; longBio: string; credentials: string[]; educationQualifications: string[]; professionalMemberships: string[]; specialties: string[]; ageGroups: string[]; populations: string[]; languages: string[]; therapyApproach: string; firstSession: string; assessmentInfo: string; referralRequirements: string; accessibility: string; insurancePaymentInfo: string; whyIAmAnSlp: string; testimonials: ProfileTestimonial[]; faqs: ProfileFaqItem[]; resources: ProfileResource[]; location: string; timezone: string; acceptsOnlineAppointments: boolean; acceptsInPersonAppointments: boolean; profileImage: string; contact: { email: string; phone: string }; socialLinks: { website: string; instagram: string; linkedin: string } };
export type EditableBookingSettings = BookingSettings & { cancellationPolicy: string; reschedulingPolicy: string; bookingInstructions: string };
const defaultProfile: EditableTherapistProfile = { name: therapistProfile.name, professionalTitle: therapistProfile.professionalTitle, shortBio: therapistProfile.shortBio, longBio: therapistProfile.longBio, credentials: [...therapistProfile.credentials], educationQualifications: [], professionalMemberships: [], specialties: [], ageGroups: [], populations: [], languages: [...therapistProfile.languages], therapyApproach: "", firstSession: "", assessmentInfo: "", referralRequirements: "", accessibility: "", insurancePaymentInfo: "", whyIAmAnSlp: "", testimonials: [], faqs: [], resources: [], location: therapistProfile.location, timezone: therapistProfile.timezone, acceptsOnlineAppointments: therapistProfile.acceptsOnlineAppointments, acceptsInPersonAppointments: therapistProfile.acceptsInPersonAppointments, profileImage: therapistProfile.profileImage, contact: { ...therapistProfile.contact }, socialLinks: { ...therapistProfile.socialLinks } };
export const defaultBookingSettings: EditableBookingSettings = { ...bookingSettings, cancellationPolicy: "", reschedulingPolicy: "", bookingInstructions: "" };
async function getCollection(): Promise<Collection<StoredDocument<unknown>>> { return (await getMongoDb()).collection<StoredDocument<unknown>>(collectionName); }
function cleanList(items: string[] | undefined): string[] { return (items ?? []).map((item) => item.trim()).filter(Boolean); }
function normalizeProfile(value: Partial<EditableTherapistProfile>): EditableTherapistProfile { return { ...defaultProfile, ...value, name: (value.name ?? "").trim(), professionalTitle: (value.professionalTitle ?? "").trim(), shortBio: (value.shortBio ?? "").trim(), longBio: (value.longBio ?? "").trim(), credentials: cleanList(value.credentials), educationQualifications: cleanList(value.educationQualifications), professionalMemberships: cleanList(value.professionalMemberships), specialties: cleanList(value.specialties), ageGroups: cleanList(value.ageGroups), populations: cleanList(value.populations), languages: cleanList(value.languages), therapyApproach: (value.therapyApproach ?? "").trim(), firstSession: (value.firstSession ?? "").trim(), assessmentInfo: (value.assessmentInfo ?? "").trim(), referralRequirements: (value.referralRequirements ?? "").trim(), accessibility: (value.accessibility ?? "").trim(), insurancePaymentInfo: (value.insurancePaymentInfo ?? "").trim(), whyIAmAnSlp: (value.whyIAmAnSlp ?? "").trim(), testimonials: (value.testimonials ?? []).map((item) => ({ quote: (item?.quote ?? "").trim(), name: (item?.name ?? "").trim(), context: (item?.context ?? "").trim() })).filter((item) => item.quote), faqs: (value.faqs ?? []).map((item) => ({ question: (item?.question ?? "").trim(), answer: (item?.answer ?? "").trim() })).filter((item) => item.question && item.answer), resources: (value.resources ?? []).map((item) => ({ title: (item?.title ?? "").trim(), description: (item?.description ?? "").trim(), url: (item?.url ?? "").trim() })).filter((item) => item.title), location: (value.location ?? "").trim(), timezone: (value.timezone ?? "").trim(), profileImage: (value.profileImage ?? "").trim(), contact: { email: (value.contact?.email ?? "").trim(), phone: (value.contact?.phone ?? "").trim() }, socialLinks: { website: (value.socialLinks?.website ?? "").trim(), instagram: (value.socialLinks?.instagram ?? "").trim(), linkedin: (value.socialLinks?.linkedin ?? "").trim() } }; }
function validateProfile(profile: EditableTherapistProfile): string | null { if (profile.shortBio.length > 500) return "Short bio must be 500 characters or fewer."; if (profile.longBio.length > 5000) return "About you must be 5,000 characters or fewer."; if ([profile.therapyApproach, profile.firstSession, profile.assessmentInfo, profile.referralRequirements, profile.accessibility, profile.insurancePaymentInfo, profile.whyIAmAnSlp].some((value) => value.length > 5000)) return "One of the profile detail sections is too long."; if (profile.testimonials.some((item) => item.quote.length > 2000 || item.name.length > 200 || item.context.length > 300)) return "One of the testimonials is too long."; if (profile.faqs.some((item) => item.question.length > 300 || item.answer.length > 3000)) return "One of the FAQ entries is too long."; if (profile.resources.some((item) => item.title.length > 200 || item.description.length > 1000 || item.url.length > 1000)) return "One of the resource entries is too long."; if (profile.location.length > 200) return "Location must be 200 characters or fewer."; if (profile.timezone) { try { new Intl.DateTimeFormat("en-US", { timeZone: profile.timezone }).format(); } catch { return "Please provide a valid IANA timezone."; } } if (profile.contact.email && !/^\S+@\S+\.\S+$/.test(profile.contact.email)) return "Please provide a valid email address."; return null; }
function normalizeBookingSettings(value: EditableBookingSettings): EditableBookingSettings { return { ...value, cancellationPolicy: value.cancellationPolicy.trim(), reschedulingPolicy: value.reschedulingPolicy.trim(), bookingInstructions: value.bookingInstructions.trim() }; }
async function getStoredProfile(id: string): Promise<EditableTherapistProfile | null> { const document = await (await getCollection()).findOne({ _id: id }) as StoredDocument<EditableTherapistProfile> | null; return document?.value ? normalizeProfile(document.value) : null; }
async function syncPublishedProfileImage(profile: EditableTherapistProfile) { if (!profile.profileImage.startsWith("/api/profile/image?draft=1") && profile.profileImage !== "") return; const bucket = new GridFSBucket(await getMongoDb(), { bucketName: profileMediaBucket }); const published = await bucket.find({ filename: publishedImageFile }).toArray(); await Promise.all(published.map((file) => bucket.delete(file._id))); if (!profile.profileImage.startsWith("/api/profile/image?draft=1")) return; const drafts = await bucket.find({ filename: draftImageFile }).sort({ uploadDate: -1 }).limit(1).toArray(); const draft = drafts[0]; if (!draft) return; const stream = bucket.openDownloadStream(draft._id); const upload = bucket.openUploadStream(publishedImageFile, { contentType: draft.contentType, metadata: { purpose: "therapist-profile-image" } }); await new Promise<void>((resolve, reject) => { stream.on("data", (chunk) => upload.write(chunk)); stream.once("end", () => upload.end()); stream.once("error", reject); upload.once("finish", resolve); upload.once("error", reject); }); }
export async function getTherapistProfile(): Promise<EditableTherapistProfile> { return (await getStoredProfile(profileId)) ?? defaultProfile; }
export async function getTherapistProfileDraft(): Promise<EditableTherapistProfile> { return (await getStoredProfile(profileDraftId)) ?? await getTherapistProfile(); }
export async function saveTherapistProfile(value: EditableTherapistProfile): Promise<EditableTherapistProfile> { return saveTherapistProfileDraft(value); }
export async function saveTherapistProfileDraft(value: EditableTherapistProfile): Promise<EditableTherapistProfile> { const profile = normalizeProfile(value); const error = validateProfile(profile); if (error) throw new Error(error); await (await getCollection()).updateOne({ _id: profileDraftId }, { $set: { value: profile, updatedAt: new Date() } }, { upsert: true }); return profile; }
export async function publishTherapistProfile(): Promise<EditableTherapistProfile> { const draft = await getTherapistProfileDraft(); const error = validateProfile(draft); if (error) throw new Error(error); await syncPublishedProfileImage(draft); const published = { ...draft, profileImage: draft.profileImage.startsWith("/api/profile/image?draft=1") ? "/api/profile/image" : draft.profileImage }; await (await getCollection()).updateOne({ _id: profileId }, { $set: { value: published, updatedAt: new Date() } }, { upsert: true }); return published; }
export async function getBookingSettings(): Promise<EditableBookingSettings> { const document = await (await getCollection()).findOne({ _id: bookingSettingsId }) as StoredDocument<EditableBookingSettings> | null; return document?.value ? normalizeBookingSettings(document.value) : defaultBookingSettings; }
export async function saveBookingSettings(value: EditableBookingSettings): Promise<EditableBookingSettings> { const settings = normalizeBookingSettings(value); const validationError = validateBookingSettings(settings); if (validationError) throw new Error(validationError); if (settings.cancellationPolicy.length > 5000 || settings.reschedulingPolicy.length > 5000 || settings.bookingInstructions.length > 5000) throw new Error("Policy and instruction fields must be 5,000 characters or fewer."); await (await getCollection()).updateOne({ _id: bookingSettingsId }, { $set: { value: settings, updatedAt: new Date() } }, { upsert: true }); return settings; }
